# frozen_string_literal: true

class EmailDomain
  PUBLIC_DOMAINS = %w[
    gmail.com
    hotmail.com
    hotmail.co.uk
    yahoo.co.uk
    outlook.com
    yahoo.com
    yahoo.fr
    yahoo.es
    yahoo.com.au
    hotmail.fr
    yahoo.ie
    yahoo.gr
    yahoo.ca
    hotmail.es
    yahoo.com.hk
    yahoo.co.in
    yahoo.it
    hotmail.it
    yahoo.de
    yahoo.co.nz
    hotmail.co.nz
    hotmail.de
    outlook.fr
    gmail.co.uk
    hotmail.ca
    hotmail.gr
    hotmail.co
    outlook.es
    outlook.ie
    yahoo.in
    yahoo.pl
    myyahoo.com
    yahoo.com.br
    gmail.co
    outlook.com.au
    yahoo.com.sg
    yahoo.ro
    yahoo.se
    gmail.con
    yahoo.co
    outlook.co.nz
    hotmail
    hotmail.com.au
    yahoo.co.jp
    outlook.co.uk
    hotmail.co.za
    outlook.it
    hotmail.co.u
    yahoo.uk
    yahoo.com.tw
    hotmail.co.uk 
    hotmail.com.uk
    hotmaill.com
    hotmail,com
    yahoo.co.au
    yahoo.com.mx
    yahoo.com.uk
    hotmaill.co.uk
    outlook.com.gr
    hotmail.co.jp
    hotmail.no
    yahoo.com.cn
    outlook.de
    hotmail.uk
    yahoo.com.ar
    yahoo.dk
    hotmail.co.ul
    hotmail.com
    yahoo.uk.co
    hotmail.co.ltd
    gmail.com
    yahoo.no
    gmail.cm
    hotmail.sg
    yahoo.co.ul
    hotmail.co.uk
    gmail.dcu.ie
    outlook.pt
    yahoo.com.tr
    yahoo.co.za
  ].freeze

  class << self
    def public?(domain)
      PUBLIC_DOMAINS.include?(domain)
    end
  end
end
