# frozen_string_literal: true

class EmailDomain
  PUBLIC_DOMAINS = %w[
    163.com
    aim.com
    alice.it
    aliceadsl.fr
    ameritech.net
    aol.co.uk
    aol.com
    aol.de
    aol.fr
    aol.it
    aol.jp
    arcor.de
    att.net
    attglobal.net
    attymail.com
    autorambler.ru
    bell.net
    bellsouth.net
    bigpond.au
    bigpond.com
    bigpond.com.au
    bigpond.net
    bigpond.net.au
    bluewin.ch
    blueyonder.co.uk
    bol.com.br
    btinternet.com
    carolina.rr.com
    centurylink.net
    cfl.rr.com
    charter.com
    charter.net
    club-internet.fr
    cogeco.ca
    comcast.com
    comcast.net
    cox.com
    cox.net
    coxinet.net
    cs.com
    cspire1.com
    earthlink.net
    email.uscc.net
    example.com
    fastmail.ca
    fastmail.cn
    fastmail.co.uk
    fastmail.com
    fastmail.com.au
    fastmail.es
    fastmail.fm
    fastmail.gr
    fastmail.im
    fastmail.in
    fastmail.jp
    fastmail.mx
    fastmail.net
    fastmail.nl
    fastmail.se
    fastmail.to
    fastmail.tw
    fastmail.us
    fastmailbox.net
    fido.ca
    freenet.de
    freenet.kg
    frontier.com
    frontiernet.net
    fulbrightmail.org
    gamil.com
    gmai.com
    gmail.co.za
    gmail.com
    gmail.com.au
    gmail.com.br
    gmail.ru
    gmx.at
    gmx.ch
    gmx.co.uk
    gmx.com
    gmx.de
    gmx.fr
    gmx.li
    gmx.net
    gmx.us
    googlemail.com
    hetnet.nl
    hotmail.be
    hotmail.ca
    hotmail.ch
    hotmail.co
    hotmail.co.il
    hotmail.co.jp
    hotmail.co.nz
    hotmail.co.uk
    hotmail.co.za
    hotmail.com
    hotmail.com.ar
    hotmail.com.au
    hotmail.com.br
    hotmail.com.mx
    hotmail.com.tr
    hotmail.de
    hotmail.es
    hotmail.fi
    hotmail.fr
    hotmail.it
    hotmail.kg
    hotmail.kz
    hotmail.my
    hotmail.nl
    hotmail.ro
    hotmail.roor
    hotmail.ru
    hushmail.com
    icloud.com
    icloud.com
    ig.com.br
    iinet.net.au
    inbox.com
    inbox.lv
    inbox.net
    inbox.ru
    inbox.si
    juno.com
    laposte.net
    libero.it
    liberomail.com
    live.at
    live.be
    live.ca
    live.cl
    live.cn
    live.co.uk
    live.co.za
    live.com
    live.com.ar
    live.com.au
    live.com.mx
    live.com.my
    live.com.pt
    live.com.sg
    live.de
    live.dk
    live.fr
    live.hk
    live.ie
    live.in
    live.it
    live.jp
    live.nl
    live.no
    live.ru
    live.se
    mac.com
    mail.az
    mail.be
    mail.bg
    mail.bulgaria.com
    mail.by
    mail.byte.it
    mail.co.za
    mail.com
    mail.com.tr
    mail.ee
    mail.gr
    mail.md
    mail.nu
    mail.org.uk
    mail.pf
    mail.pt
    mail.ru
    mail.svenz.eu
    mail.usa.com
    mail.vu
    mail.wtf
    mail.zp.ua
    mailinatar.com
    mailinater.com
    mailinator.com
    mailinator.net
    mailinator.org
    mailinator.us
    mailinator2.com
    me.com
    msg.telus.com
    msn.cn
    msn.com
    msn.nl
    mymetropcs.com
    myrambler.ru
    myyahoo.com
    naver.com
    nc.rr.com
    netscape.net
    netzero.net
    neuf.fr
    ntlworld.com
    optimum.net
    optonline.net
    optusnet.com.au
    orange.fr
    orange.net
    outlook.at
    outlook.be
    outlook.cl
    outlook.co.id
    outlook.co.il
    outlook.co.nz
    outlook.co.th
    outlook.com
    outlook.com.au
    outlook.com.br
    outlook.com.gr
    outlook.com.pe
    outlook.com.tr
    outlook.com.vn
    outlook.cz
    outlook.de
    outlook.dk
    outlook.es
    outlook.fr
    outlook.hu
    outlook.ie
    outlook.in
    outlook.it
    outlook.jp
    outlook.kr
    outlook.lv
    outlook.my
    outlook.nl
    outlook.ph
    outlook.pt
    outlook.sa
    outlook.sg
    outlook.sk
    pacbell.net
    pcs.rogers.com
    planet.nl
    proton.me
    protonmail.ch
    protonmail.com
    ptd.net
    qq.com
    ramber.ru
    rediff.com
    rediffmail.com
    rediffmailpro.com
    roadrunner.com
    rocketmail.com
    rogers.com
    sbcglbal.net
    sbcglobal.com
    sbcglobal.net
    sfr.fr
    shaw.ca
    sky.com
    suddenlink.net
    sympatico.ca
    tampabay.rr.com
    tds.net
    telenet.be
    telus.net
    terra.cl
    terra.com
    terra.com.ar
    terra.com.br
    terra.com.pe
    terra.es
    tin.it
    tiscali.at
    tiscali.be
    tiscali.co.uk
    tiscali.it
    tiscali.lu
    tiscali.se
    tmomail.net
    t-online.de
    tuta.io
    tutamail.com
    tutanota.com
    tutanota.de
    twc.com
    txt.att.net
    txt.bell.ca
    txt.freedommobile.ca
    ukr.net
    uol.com.ar
    uol.com.br
    uol.com.co
    uol.com.mx
    uol.com.ve
    uole.com
    uole.com.ve
    uolmail.com
    verizon.net
    verizonmail.com
    videotron.ca
    virgilio.it
    virgin.net
    virginbroadband.com.au
    virginmedia.com
    voila.fr
    vtext.com
    wanadoo.co.uk
    wanadoo.es
    wanadoo.fr
    web.de
    windstream.net
    woh.rr.com
    wp.pl
    y7mail.com
    yahoo.ae
    yahoo.at
    yahoo.be
    yahoo.ca
    yahoo.ch
    yahoo.cn
    yahoo.co
    yahoo.co.id
    yahoo.co.il
    yahoo.co.in
    yahoo.co.jp
    yahoo.co.kr
    yahoo.co.nz
    yahoo.co.th
    yahoo.co.uk
    yahoo.co.za
    yahoo.com
    yahoo.com.ar
    yahoo.com.au
    yahoo.com.br
    yahoo.com.cn
    yahoo.com.co
    yahoo.com.hk
    yahoo.com.is
    yahoo.com.mx
    yahoo.com.my
    yahoo.com.ph
    yahoo.com.ru
    yahoo.com.sg
    yahoo.com.tr
    yahoo.com.tw
    yahoo.com.vn
    yahoo.cz
    yahoo.de
    yahoo.dk
    yahoo.es
    yahoo.fi
    yahoo.fr
    yahoo.gr
    yahoo.hu
    yahoo.ie
    yahoo.in
    yahoo.it
    yahoo.jp
    yahoo.net
    yahoo.nl
    yahoo.no
    yahoo.pl
    yahoo.pt
    yahoo.ro
    yahoo.ru
    yahoo.se
    yandex.com
    yandex.mail
    yandex.pl
    yandex.ru
    yandex.ua
    ymail.com
    zoho.com
    zonnet.nl
  ].freeze

  class << self
    def public?(domain)
      PUBLIC_DOMAINS.include?(domain)
    end
  end
end
