inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_mode:
  merge:
    - Exclude

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/BlockDelimiters:
  Exclude:
    - app/models/feature_flag.rb

Style/MethodCalledOnDoEndBlock:
  Exclude:
    - app/models/feature_flag.rb

Layout/LineLength:
  Exclude:
    - spec/helpers/application_form_helper_spec.rb

Lint/SuppressedException:
  Exclude:
    - spec/jobs/update_dqt_trn_request_job_spec.rb
