inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_mode:
  merge:
    - Exclude

Rails/SaveBang:
  Exclude:
    - error_log/spec/**/*

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/BlockDelimiters:
  Exclude:
    - app/models/feature_flag.rb

Style/MethodCalledOnDoEndBlock:
  Exclude:
    - app/models/feature_flag.rb
