inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_mode:
  merge:
    - Exclude

Layout/EmptyLineAfterMagicComment:
  Enabled: true

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
