name: Deploy environment
description: Deploys an application environment

inputs:
  environment:
    description: The name of the environment
    required: true
  docker-image:
    description: The Docker image to deploy
    required: true
  azure-credentials:
    description: JSON object containing a service principal that can read from Azure Key Vault
    required: true
  pull-request-number:
    description: The pull request number which triggered this deploy. If set, this will automatically seed the database.
    required: false
  smoke-test-credentials-required:
    description: Whether to run the smoke test with support credentials
    required: false
    default: "true"

outputs:
  url:
    description: The base URL for the deployed environment
    value: ${{ steps.apply-terraform.outputs.url }}

runs:
  using: composite

  steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0
        terraform_wrapper: false

    - uses: DFE-Digital/github-actions/set-arm-environment-variables@master
      with:
        azure-credentials: ${{ inputs.azure-credentials }}

    - name: Apply Terraform
      id: apply-terraform
      shell: bash
      run: |
        make ci ${{ inputs.environment }} terraform-apply
        cd terraform/application && echo "url=$(terraform output -raw url)" >> $GITHUB_OUTPUT
      env:
        TF_VAR_azure_sp_credentials_json: ${{ inputs.azure-credentials }}
        DOCKER_IMAGE: ${{ inputs.docker-image }}
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}

    - uses: Azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}

    - name: Seed database
      if: ${{ inputs.pull-request-number != '' }}
      shell: bash
      run: |
        az aks get-credentials -g s189t01-tsc-ts-rg -n s189t01-tsc-test-aks
        kubectl exec -n tra-development deployment/apply-for-qts-review-${{ inputs.pull-request-number }}-web -- sh -c "cd /app && /usr/local/bin/bundle exec rails db:seed review_app:configure example_data:generate"

    - id: key-vault-name
      if: ${{ inputs.smoke-test-credentials-required == 'true' }}
      shell: bash
      run: echo "value=$(make -s ${{ inputs.environment }} print-application-key-vault-name)" >> $GITHUB_OUTPUT
      env:
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}

    - uses: Azure/get-keyvault-secrets@v1
      id: smoke-test-secrets
      if: ${{ inputs.smoke-test-credentials-required == 'true' }}
      with:
        keyvault: ${{ steps.key-vault-name.outputs.value }}
        secrets: "SUPPORT-USERNAME,SUPPORT-PASSWORD"

    - uses: ./.github/actions/smoke-test
      with:
        url: ${{ steps.apply-terraform.outputs.url }}
        username: ${{ steps.smoke-test-secrets.outputs.SUPPORT-USERNAME }}
        password: ${{ steps.smoke-test-secrets.outputs.SUPPORT-PASSWORD }}
