name: Deploy environment
description: Deploys an application environment

inputs:
  environment:
    description: The name of the environment
    required: true
  docker-image:
    description: The Docker image to deploy
    required: true
  pull-request-number:
    description: The pull request number which triggered this deploy. If set, this will automatically seed the database.
    required: false
  smoke-test-credentials-required:
    description: Whether to run the smoke test with support credentials
    required: false
    default: "true"
  azure-client-id:
    description: Managed identity client ID
    required: true
  azure-subscription-id:
    description: Azure subscription ID
    required: true
  azure-tenant-id:
    description: Azure tenant ID
    required: true

outputs:
  url:
    description: The base URL for the deployed environment
    value: ${{ steps.apply-terraform.outputs.url }}

runs:
  using: composite

  steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0
        terraform_wrapper: false

    - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-client-id: ${{ inputs.azure-client-id }}
        azure-tenant-id: ${{ inputs.azure-tenant-id }}
        azure-subscription-id: ${{ inputs.azure-subscription-id }}

    - uses: google-github-actions/auth@v2
      with:
        project_id: apply-for-qts-in-england
        workload_identity_provider: projects/385922361840/locations/global/workloadIdentityPools/apply-for-qualified-teacher-sta3/providers/apply-for-qualified-teacher-sta3

    - name: Apply Terraform
      id: apply-terraform
      shell: bash
      run: |
        make ci ${{ inputs.environment }} terraform-apply
        cd terraform/application && echo "url=$(terraform output -raw url)" >> $GITHUB_OUTPUT
      env:
        DOCKER_IMAGE: ${{ inputs.docker-image }}
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}

    - uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Seed database
      if: ${{ inputs.pull-request-number != '' }}
      shell: bash
      run: |
        make ci review get-cluster-credentials
        kubectl exec -n tra-development deployment/apply-for-qts-review-${PULL_REQUEST_NUMBER}-web -- sh -c "cd /app && /usr/local/bin/bundle exec rails db:seed review_app:configure fake_data:generate"
      env:
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}

    - id: key-vault-name
      if: ${{ inputs.smoke-test-credentials-required == 'true' }}
      shell: bash
      run: echo "value=$(make -s ${{ inputs.environment }} print-application-key-vault-name)" >> $GITHUB_OUTPUT
      env:
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}

    - uses: Azure/get-keyvault-secrets@v1
      id: smoke-test-secrets
      if: ${{ inputs.smoke-test-credentials-required == 'true' }}
      with:
        keyvault: ${{ steps.key-vault-name.outputs.value }}
        secrets: "SUPPORT-USERNAME,SUPPORT-PASSWORD"

    - uses: ./.github/actions/smoke-test
      with:
        url: ${{ steps.apply-terraform.outputs.url }}
        username: ${{ steps.smoke-test-secrets.outputs.SUPPORT-USERNAME }}
        password: ${{ steps.smoke-test-secrets.outputs.SUPPORT-PASSWORD }}
