name: Set Kubernetes Credentials
description: Sets the credentials suitable for kubectl

inputs:
  environment:
    description: The name of the environment
    required: true
  azure-credentials:
    description: JSON object containing a service principal that can read from Azure Key Vault
    required: true

runs:
  using: composite

  steps:
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
        terraform_wrapper: false

    - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-credentials: ${{ inputs.azure-credentials }}

    - uses: Azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}

    - name: Set AKS credentials
      shell: bash
      run: make ci ${{ inputs.environment }} get-cluster-credentials
