name: Prepare application environment
description: Performs setup steps common to jobs that need to run the application
inputs:
  skip-node:
    description: Allows skipping Node.js setup for jobs where it isn't required
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Update apt
      run: sudo rm /etc/apt/sources.list.d/microsoft-prod.list && sudo apt-get update
      shell: bash

    - name: Install libvips
      run: sudo apt install -y libvips
      shell: bash

    - name: Install libmagickwand
      run: sudo apt-get install libmagickwand-dev
      shell: bash

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Set up Node
      if: ${{ inputs.skip-node == 'false' }}
      uses: actions/setup-node@v7
      with:
        node-version-file: .tool-versions
        package-manager-cache: false

    - name: Enable corepack
      if: ${{ inputs.skip-node == 'false' }}
      run: corepack enable
      shell: bash

    - name: Install node.js dependencies
      if: ${{ inputs.skip-node == 'false' }}
      run: yarn install --immutable
      shell: bash
