---
TRS_API_URL: https://teacher-qualifications-api.education.gov.uk
DEFAULT_QUEUE_THREADS: 3
DEFAULT_QUEUE_PROCESSES: 1
MAILER_QUEUE_THREADS: 1
MAILER_QUEUE_PROCESSES: 1
ANALYTICS_QUEUE_THREADS: 1
ANALYTICS_QUEUE_PROCESSES: 1
