name: Smoke test
description: Run the smoke tests against a live environment.

inputs:
  url:
    description: The URL of the deployed environment.
    required: true
  username:
    description: The HTTP username to access the service.
    required: false
  password:
    description: The HTTP password to access the service.
    required: false

runs:
  using: composite

  steps:
    - name: Prepare application environment
      uses: ./.github/actions/prepare-app-env

    - name: Run smoke tests
      shell: bash
      run: bin/smoke
      env:
        RAILS_ENV: test
        SMOKE_URL: ${{ inputs.url }}
        SMOKE_USERNAME: ${{ inputs.username }}
        SMOKE_PASSWORD: ${{ inputs.password }}
