:shared:
  :application_forms:
    - action_required_by
    - age_range_max
    - age_range_min
    - age_range_status
    - alternative_family_name
    - alternative_given_names
    - assessor_id
    - awarded_at
    - confirmed_no_sanctions
    - created_at
    - date_of_birth
    - declined_at
    - dqt_match
    - english_language_citizenship_exempt
    - english_language_proof_method
    - english_language_provider_id
    - english_language_provider_other
    - english_language_provider_reference
    - english_language_qualification_exempt
    - english_language_status
    - family_name
    - given_names
    - has_alternative_name
    - has_work_history
    - id
    - identification_document_status
    - needs_registration_number
    - needs_work_history
    - needs_written_statement
    - personal_information_status
    - qualification_changed_work_history_duration
    - qualifications_status
    - reduced_evidence_accepted
    - reference
    - region_id
    - registration_number
    - registration_number_status
    - requires_preliminary_check
    - reviewer_id
    - stage
    - statuses
    - subject_limited
    - subjects
    - subjects_status
    - submitted_at
    - teacher_id
    - teaching_authority_provides_written_statement
    - teaching_qualification_part_of_degree
    - updated_at
    - withdrawn_at
    - work_history_status
    - working_days_since_submission
    - written_statement_confirmation
    - written_statement_optional
    - written_statement_status
  :application_forms_suitability_records:
    - application_form_id
    - suitability_record_id
  :assessment_sections:
    - assessed_at
    - assessment_id
    - checks
    - created_at
    - failure_reasons
    - id
    - key
    - passed
    - preliminary
    - updated_at
  :assessments:
    - age_range_max
    - age_range_min
    - application_form_id
    - created_at
    - id
    - induction_required
    - recommendation
    - recommended_at
    - references_verified
    - scotland_full_registration
    - started_at
    - subjects
    - unsigned_consent_document_generated
    - updated_at
    - working_days_since_started
    - working_days_started_to_recommendation
    - working_days_submission_to_recommendation
    - working_days_submission_to_started
  :consent_requests:
    - assessment_id
    - created_at
    - expired_at
    - id
    - qualification_id
    - received_at
    - requested_at
    - review_passed
    - reviewed_at
    - unsigned_document_downloaded
    - updated_at
    - verified_at
    - verify_passed
  :countries:
    - code
    - created_at
    - eligibility_enabled
    - eligibility_skip_questions
    - id
    - subject_limited
    - updated_at
  :documents:
    - available
    - created_at
    - document_type
    - documentable_id
    - documentable_type
    - id
    - updated_at
  :dqt_trn_requests:
    - application_form_id
    - created_at
    - id
    - potential_duplicate
    - request_id
    - state
    - updated_at
  :eligibility_checks:
    - completed_at
    - country_code
    - created_at
    - degree
    - free_of_sanctions
    - id
    - qualification
    - qualified_for_subject
    - region_id
    - teach_children
    - updated_at
    - work_experience
  :english_language_providers:
    - accepted_tests
    - b2_level_requirement
    - b2_level_requirement_prefix
    - check_url
    - created_at
    - id
    - name
    - reference_hint
    - reference_name
    - updated_at
    - url
  :further_information_requests:
    - assessment_id
    - created_at
    - expired_at
    - id
    - received_at
    - requested_at
    - review_passed
    - reviewed_at
    - updated_at
    - working_days_assessment_started_to_creation
    - working_days_received_to_recommendation
    - working_days_since_received
  :further_information_request_items:
    - contact_email
    - contact_job
    - contact_name
    - created_at
    - failure_reason_key
    - further_information_request_id
    - id
    - information_type
    - updated_at
    - work_history_id
  :mail_delivery_failures:
    - created_at
    - email_address
    - id
    - mailer_action_method
    - mailer_class
    - updated_at
  :notes:
    - application_form_id
    - author_id
    - created_at
    - id
    - updated_at
  :professional_standing_requests:
    - assessment_id
    - created_at
    - expired_at
    - id
    - received_at
    - requested_at
    - review_passed
    - reviewed_at
    - updated_at
    - verified_at
    - verify_passed
  :qualifications:
    - application_form_id
    - certificate_date
    - complete_date
    - created_at
    - id
    - institution_country_code
    - institution_name
    - start_date
    - title
    - updated_at
  :qualification_requests:
    - assessment_id
    - consent_method
    - created_at
    - expired_at
    - id
    - qualification_id
    - received_at
    - requested_at
    - review_passed
    - reviewed_at
    - updated_at
    - verified_at
    - verify_passed
  :reference_requests:
    - assessment_id
    - children_response
    - contact_job
    - contact_name
    - contact_response
    - created_at
    - dates_response
    - expired_at
    - hours_response
    - id
    - lessons_response
    - misconduct_response
    - received_at
    - reports_response
    - requested_at
    - review_passed
    - reviewed_at
    - satisfied_response
    - updated_at
    - verified_at
    - verify_passed
    - work_history_id
  :regions:
    - application_form_skip_work_history
    - country_id
    - created_at
    - id
    - name
    - reduced_evidence_accepted
    - requires_preliminary_check
    - sanction_check
    - status_check
    - teaching_authority_address
    - teaching_authority_certificate
    - teaching_authority_emails
    - teaching_authority_name
    - teaching_authority_online_checker_url
    - teaching_authority_provides_written_statement
    - teaching_authority_requires_submission_email
    - teaching_authority_websites
    - updated_at
    - written_statement_optional
  :reminder_emails:
    - created_at
    - id
    - name
    - remindable_id
    - remindable_type
    - updated_at
  :selected_failure_reasons:
    - assessment_section_id
    - created_at
    - id
    - key
    - updated_at
  :selected_failure_reasons_work_histories:
    - selected_failure_reason_id
    - work_history_id
  :staff:
    - assess_permission
    - change_email_permission
    - change_name_permission
    - change_work_history_permission
    - confirmation_sent_at
    - confirmed_at
    - created_at
    - current_sign_in_at
    - current_sign_in_ip
    - email
    - failed_attempts
    - id
    - invitation_accepted_at
    - invitation_created_at
    - invitation_limit
    - invitation_sent_at
    - invitations_count
    - invited_by_id
    - invited_by_type
    - last_sign_in_at
    - last_sign_in_ip
    - locked_at
    - name
    - remember_created_at
    - reset_password_sent_at
    - reverse_decision_permission
    - sign_in_count
    - support_console_permission
    - unconfirmed_email
    - updated_at
    - verify_permission
    - withdraw_permission
  :suitability_record_emails:
    - canonical
    - created_at
    - id
    - suitability_record_id
    - updated_at
    - value
  :suitability_record_names:
    - created_at
    - id
    - suitability_record_id
    - updated_at
    - value
  :suitability_records:
    - archived_at
    - country_code
    - created_at
    - date_of_birth
    - id
    - updated_at
  :teachers:
    - canonical_email
    - created_at
    - current_sign_in_at
    - current_sign_in_ip
    - email
    - email_domain
    - id
    - last_sign_in_at
    - last_sign_in_ip
    - sign_in_count
    - trn
    - updated_at
    - uuid
  :uploads:
    - created_at
    - document_id
    - id
    - malware_scan_result
    - translation
    - updated_at
  :work_histories:
    - application_form_id
    - canonical_contact_email
    - city
    - contact_email
    - contact_email_domain
    - contact_job
    - contact_name
    - country_code
    - created_at
    - end_date
    - end_date_is_estimate
    - hours_per_week
    - id
    - job
    - school_name
    - start_date
    - start_date_is_estimate
    - still_employed
    - updated_at
