---
:shared:
  :application_forms:
    - given_names
    - family_name
    - date_of_birth
    - age_range_min
    - age_range_max
  :work_histories:
    - school_name
    - city
    - country
    - job
    - email
    - start_date
    - still_employed
    - end_date
