---
:shared:
  :active_storage_variant_records:
    - id
    - blob_id
    - variation_digest
  :active_storage_blobs:
    - id
    - key
    - filename
    - content_type
    - metadata
    - service_name
    - byte_size
    - checksum
    - created_at
  :active_storage_attachments:
    - id
    - name
    - record_type
    - record_id
    - blob_id
    - created_at
  :application_forms:
    - id
    - reference
    - state
    - personal_information_status
    - identification_document_status
    - qualifications_status
    - age_range_status
    - subjects_status
    - work_history_status
    - registration_number_status
    - written_statement_status
    - teacher_id
    - created_at
    - updated_at
    - given_names
    - family_name
    - date_of_birth
    - age_range_min
    - age_range_max
    - has_alternative_name
    - alternative_given_names
    - alternative_family_name
    - region_id
    - registration_number
    - has_work_history
    - subjects
    - assessor_id
    - reviewer_id
    - submitted_at
    - awarded_at
    - working_days_since_submission
    - needs_work_history
    - needs_written_statement
    - needs_registration_number
    - confirmed_no_sanctions
    - english_language_status
    - english_language_citizenship_exempt
    - english_language_qualification_exempt
    - english_language_proof_method
    - english_language_provider_id
    - english_language_provider_reference
  :assessment_sections:
    - id
    - assessment_id
    - key
    - passed
    - checks
    - failure_reasons
    - created_at
    - updated_at
  :assessments:
    - id
    - application_form_id
    - recommendation
    - created_at
    - updated_at
    - started_at
    - age_range_min
    - age_range_max
    - age_range_note
    - subjects
    - subjects_note
    - recommended_at
    - working_days_since_started
    - working_days_submission_to_recommendation
    - working_days_submission_to_started
    - working_days_started_to_recommendation
  :countries:
    - id
    - code
    - created_at
    - updated_at
    - teaching_authority_address
    - teaching_authority_emails
    - teaching_authority_websites
    - teaching_authority_certificate
    - teaching_authority_other
    - teaching_authority_name
    - teaching_authority_checks_sanctions
    - teaching_authority_online_checker_url
    - teaching_authority_status_information
    - teaching_authority_sanction_information
  :documents:
    - id
    - document_type
    - documentable_type
    - documentable_id
    - created_at
    - updated_at
  :dqt_trn_requests:
    - id
    - application_form_id
    - request_id
    - state
    - created_at
    - updated_at
  :eligibility_checks:
    - id
    - free_of_sanctions
    - created_at
    - updated_at
    - teach_children
    - qualification
    - degree
    - country_code
    - region_id
    - completed_at
    - completed_requirements
    - work_experience
  :english_language_providers:
    - id
    - name
    - b2_level_requirement
    - reference_name
    - reference_hint
    - created_at
    - updated_at
  :feature_flags_features:
    - id
    - name
    - active
    - created_at
    - updated_at
  :further_information_requests:
    - id
    - received_at
    - state
    - created_at
    - updated_at
    - assessment_id
    - passed
    - failure_assessor_note
    - working_days_since_received
    - working_days_received_to_recommendation
  :further_information_request_items:
    - id
    - information_type
    - created_at
    - updated_at
    - further_information_request_id
    - failure_reason_key
    - failure_reason_assessor_feedback
    - response
  :notes:
    - id
    - application_form_id
    - author_id
    - text
    - created_at
    - updated_at
  :qualifications:
    - id
    - application_form_id
    - title
    - institution_name
    - institution_country_code
    - start_date
    - complete_date
    - certificate_date
    - created_at
    - updated_at
    - part_of_university_degree
  :regions:
    - id
    - country_id
    - name
    - created_at
    - updated_at
    - status_check
    - sanction_check
    - teaching_authority_address
    - legacy
    - teaching_authority_emails
    - teaching_authority_websites
    - teaching_authority_name
    - teaching_authority_other
    - teaching_authority_certificate
    - teaching_authority_online_checker_url
    - application_form_enabled
    - teaching_authority_status_information
    - teaching_authority_sanction_information
  :reminder_emails:
    - id
    - created_at
    - updated_at
    - further_information_request_id
  :selected_failure_reasons:
    - id
    - created_at
    - updated_at
    - key
    - assessor_feedback
    - assessment_section_id
  :staff:
    - id
    - email
    - reset_password_sent_at
    - remember_created_at
    - sign_in_count
    - current_sign_in_at
    - last_sign_in_at
    - current_sign_in_ip
    - last_sign_in_ip
    - confirmed_at
    - confirmation_sent_at
    - unconfirmed_email
    - failed_attempts
    - locked_at
    - created_at
    - updated_at
    - invitation_created_at
    - invitation_sent_at
    - invitation_accepted_at
    - invitation_limit
    - invited_by_type
    - invited_by_id
    - invitations_count
    - name
    - award_decline_permission
    - support_console_permission
  :teachers:
    - id
    - uuid
    - email
    - created_at
    - updated_at
    - sign_in_count
    - current_sign_in_at
    - last_sign_in_at
    - current_sign_in_ip
    - last_sign_in_ip
    - trn
    - otp_guesses
    - otp_created_at
  :timeline_events:
    - id
    - event_type
    - application_form_id
    - annotation
    - creator_id
    - creator_type
    - creator_name
    - created_at
    - updated_at
    - assignee_id
    - old_state
    - new_state
    - assessment_section_id
    - note_id
    - further_information_request_id
    - mailer_action_name
    - message_subject
    - assessment_id
  :uploads:
    - id
    - document_id
    - translation
    - created_at
    - updated_at
  :work_histories:
    - id
    - application_form_id
    - school_name
    - city
    - country_code
    - job
    - contact_email
    - contact_name
    - start_date
    - still_employed
    - end_date
    - created_at
    - updated_at
