---
:shared:
  :regions:
    - id
    - country_id
    - name
    - created_at
    - updated_at
    - status_check
    - sanction_check
    - teaching_authority_address
    - teaching_authority_emails
    - teaching_authority_websites
    - teaching_authority_name
    - legacy
  :features:
    - id
    - name
    - active
    - created_at
    - updated_at
  :eligibility_checks:
    - id
    - free_of_sanctions
    - created_at
    - updated_at
    - teach_children
    - qualification
    - degree
    - country_code
    - region_id
    - completed_at
    - completed_requirements
  :countries:
    - id
    - code
    - created_at
    - updated_at
    - teaching_authority_certificate
    - teaching_authority_other
    - teaching_authority_address
    - teaching_authority_emails
    - teaching_authority_websites
    - teaching_authority_name
  :application_forms:
    - id
    - reference
    - status
    - teacher_id
    - region_id
    - created_at
    - updated_at
    - given_names
    - family_name
    - date_of_birth
    - age_range_min
    - age_range_max
    - has_alternative_name
    - alternative_given_names
    - alternative_family_name
    - registration_number
    - has_work_history
  :work_histories:
    - id
    - application_form_id
    - school_name
    - city
    - country
    - job
    - email
    - start_date
    - still_employed
    - end_date
    - created_at
    - updated_at
  :qualifications:
    - id
    - application_form_id
    - title
    - institution_name
    - institution_country
    - start_date
    - complete_date
    - certificate_date
    - created_at
    - updated_at
