---
:shared:
  :active_storage_blobs:
    - filename
  :active_storage_attachments:
    - name
  :application_forms:
    - given_names
    - family_name
    - date_of_birth
    - age_range_min
    - age_range_max
    - has_alternative_name
    - alternative_given_names
    - alternative_family_name
    - registration_number
    - has_work_history
    - subjects
  :further_information_requests:
    - failure_assessor_note
  :further_information_request_items:
    - failure_reason_assessor_feedback
    - response
  :notes:
    - text
  :professional_standing_requests:
    - location_note
  :qualifications:
    - title
    - institution_name
    - institution_country_code
    - start_date
    - complete_date
    - certificate_date
    - part_of_university_degree
  :reference_requests:
    - additional_information_response
  :selected_failure_reasons:
    - assessor_feedback
  :staff:
    - email
    - unconfirmed_email
    - current_sign_in_ip
    - last_sign_in_ip
    - name
  :teachers:
    - email
    - unconfirmed_email
    - current_sign_in_ip
    - last_sign_in_ip
  :work_histories:
    - school_name
    - city
    - country_code
    - job
    - email
    - start_date
    - still_employed
    - end_date
