---
:shared:
  :active_storage_variant_records:
    - id
    - blob_id
    - variation_digest
  :active_storage_blobs:
    - id
    - key
    - filename
    - content_type
    - metadata
    - service_name
    - byte_size
    - checksum
    - created_at
  :active_storage_attachments:
    - id
    - name
    - record_type
    - record_id
    - blob_id
    - created_at
  :application_forms:
    - id
    - reference
    - status
    - overdue_further_information
    - overdue_professional_standing
    - overdue_qualification
    - overdue_reference
    - received_further_information
    - received_professional_standing
    - received_qualification
    - received_reference
    - waiting_on_further_information
    - waiting_on_professional_standing
    - waiting_on_qualification
    - waiting_on_reference
    - personal_information_status
    - identification_document_status
    - qualifications_status
    - age_range_status
    - subjects_status
    - work_history_status
    - registration_number_status
    - written_statement_status
    - teacher_id
    - created_at
    - updated_at
    - given_names
    - family_name
    - date_of_birth
    - age_range_min
    - age_range_max
    - has_alternative_name
    - alternative_given_names
    - alternative_family_name
    - region_id
    - registration_number
    - has_work_history
    - subjects
    - assessor_id
    - reviewer_id
    - submitted_at
    - awarded_at
    - declined_at
    - withdrawn_at
    - working_days_since_submission
    - needs_work_history
    - needs_written_statement
    - needs_registration_number
    - teaching_authority_provides_written_statement
    - written_statement_confirmation
    - written_statement_optional
    - confirmed_no_sanctions
    - english_language_status
    - english_language_citizenship_exempt
    - english_language_qualification_exempt
    - english_language_proof_method
    - english_language_provider_id
    - english_language_provider_other
    - english_language_provider_reference
    - reduced_evidence_accepted
    - requires_preliminary_check
    - dqt_match
  :assessment_sections:
    - id
    - assessment_id
    - preliminary
    - key
    - passed
    - checks
    - failure_reasons
    - created_at
    - updated_at
  :assessments:
    - age_range_max
    - age_range_min
    - age_range_note
    - application_form_id
    - created_at
    - id
    - induction_required
    - recommendation
    - recommendation_assessor_note
    - recommended_at
    - references_verified
    - scotland_full_registration
    - started_at
    - subjects
    - subjects_note
    - updated_at
    - working_days_since_started
    - working_days_started_to_recommendation
    - working_days_submission_to_recommendation
    - working_days_submission_to_started
  :countries:
    - id
    - code
    - created_at
    - updated_at
    - eligibility_enabled
    - eligibility_skip_questions
    - teaching_authority_address
    - teaching_authority_emails
    - teaching_authority_websites
    - teaching_authority_certificate
    - teaching_authority_other
    - teaching_authority_name
    - teaching_authority_online_checker_url
    - teaching_authority_status_information
    - teaching_authority_sanction_information
    - qualifications_information
    - requires_preliminary_check
  :documents:
    - available
    - completed
    - created_at
    - document_type
    - documentable_id
    - documentable_type
    - id
    - updated_at
  :dqt_trn_requests:
    - id
    - application_form_id
    - request_id
    - state
    - potential_duplicate
    - created_at
    - updated_at
  :eligibility_checks:
    - id
    - free_of_sanctions
    - created_at
    - updated_at
    - teach_children
    - qualification
    - degree
    - country_code
    - region_id
    - completed_at
    - work_experience
    - qualified_for_subject
  :english_language_providers:
    - id
    - name
    - b2_level_requirement
    - b2_level_requirement_prefix
    - url
    - reference_name
    - reference_hint
    - accepted_tests
    - check_url
    - created_at
    - updated_at
  :feature_flags_features:
    - id
    - name
    - active
    - created_at
    - updated_at
  :further_information_requests:
    - id
    - received_at
    - state
    - created_at
    - updated_at
    - assessment_id
    - passed
    - failure_assessor_note
    - working_days_since_received
    - working_days_received_to_recommendation
    - working_days_assessment_started_to_creation
    - reviewed_at
  :further_information_request_items:
    - id
    - information_type
    - created_at
    - updated_at
    - further_information_request_id
    - failure_reason_key
    - failure_reason_assessor_feedback
    - response
    - contact_name
    - contact_job
    - contact_email
    - work_history_id
  :notes:
    - id
    - application_form_id
    - author_id
    - text
    - created_at
    - updated_at
  :professional_standing_requests:
    - id
    - assessment_id
    - state
    - received_at
    - location_note
    - created_at
    - updated_at
    - reviewed_at
    - passed
    - failure_assessor_note
    - ready_for_review
  :qualifications:
    - id
    - application_form_id
    - title
    - institution_name
    - institution_country_code
    - start_date
    - complete_date
    - certificate_date
    - created_at
    - updated_at
    - part_of_university_degree
  :qualification_requests:
    - id
    - assessment_id
    - qualification_id
    - state
    - received_at
    - location_note
    - created_at
    - updated_at
    - reviewed_at
    - passed
    - failure_assessor_note
  :reference_requests:
    - id
    - slug
    - assessment_id
    - work_history_id
    - state
    - received_at
    - contact_response
    - contact_name
    - contact_job
    - contact_comment
    - dates_response
    - dates_comment
    - hours_response
    - hours_comment
    - children_response
    - children_comment
    - lessons_response
    - lessons_comment
    - reports_response
    - reports_comment
    - misconduct_response
    - misconduct_comment
    - satisfied_response
    - satisfied_comment
    - additional_information_response
    - created_at
    - updated_at
    - passed
    - failure_assessor_note
    - reviewed_at
  :regions:
    - id
    - country_id
    - name
    - created_at
    - updated_at
    - status_check
    - sanction_check
    - application_form_skip_work_history
    - reduced_evidence_accepted
    - teaching_authority_address
    - teaching_authority_emails
    - teaching_authority_websites
    - teaching_authority_name
    - teaching_authority_other
    - teaching_authority_certificate
    - teaching_authority_online_checker_url
    - teaching_authority_status_information
    - teaching_authority_sanction_information
    - teaching_authority_provides_written_statement
    - teaching_authority_requires_submission_email
    - qualifications_information
    - written_statement_optional
    - requires_preliminary_check
  :reminder_emails:
    - id
    - created_at
    - updated_at
    - remindable_id
    - remindable_type
  :selected_failure_reasons:
    - id
    - created_at
    - updated_at
    - key
    - assessor_feedback
    - assessment_section_id
  :selected_failure_reasons_work_histories:
    - work_history_id
    - selected_failure_reason_id
    - work_history_id
    - selected_failure_reason_id
  :staff:
    - award_decline_permission
    - azure_ad_uid
    - confirmation_sent_at
    - confirmed_at
    - created_at
    - current_sign_in_at
    - current_sign_in_ip
    - email
    - failed_attempts
    - id
    - invitation_accepted_at
    - invitation_created_at
    - invitation_limit
    - invitation_sent_at
    - invitations_count
    - invited_by_id
    - invited_by_type
    - last_sign_in_at
    - last_sign_in_ip
    - locked_at
    - manage_applications_permission
    - name
    - remember_created_at
    - reset_password_sent_at
    - sign_in_count
    - support_console_permission
    - unconfirmed_email
    - updated_at
  :teachers:
    - canonical_email
    - created_at
    - current_sign_in_at
    - current_sign_in_ip
    - email
    - id
    - last_sign_in_at
    - last_sign_in_ip
    - otp_created_at
    - otp_guesses
    - sign_in_count
    - trn
    - updated_at
    - uuid
  :timeline_events:
    - age_range_max
    - age_range_min
    - age_range_note
    - application_form_id
    - assessment_id
    - assessment_section_id
    - assignee_id
    - column_name
    - created_at
    - creator_id
    - creator_name
    - creator_type
    - event_type
    - id
    - mailer_action_name
    - mailer_class_name
    - message_subject
    - new_state
    - new_value
    - note_id
    - old_state
    - old_value
    - requestable_id
    - requestable_type
    - subjects
    - subjects_note
    - updated_at
    - work_history_id
  :uploads:
    - id
    - document_id
    - translation
    - created_at
    - updated_at
    - malware_scan_result
  :work_histories:
    - application_form_id
    - canonical_contact_email
    - city
    - contact_email
    - contact_job
    - contact_name
    - country_code
    - created_at
    - end_date
    - end_date_is_estimate
    - end_date_is_estimate
    - hours_per_week
    - id
    - job
    - school_name
    - start_date
    - start_date_is_estimate
    - still_employed
    - updated_at
