default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres@localhost:5432') %>

development:
  <<: *default
  database: apply_for_qts_development

test:
  <<: *default
  database: apply_for_qts_test

production:
  <<: *default
  database: apply_for_qts_production
