default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [default, mailer, analytics]
      threads: 3
      processes: 10
      polling_interval: 1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
