production:
  clear_solid_queue_finished_jobs:
    class: "ClearSolidQueueFinishedJobsJob"
    schedule: every hour at minute 12
  destroy_abandoned_draft_application_forms:
    class: "DestroyApplicationFormsJob"
    schedule: "15 1 * * *"
  trim_sessions_job:
    class: "TrimSessionsJob"
    schedule: "0 1 * * *"
  update_working_days:
    class: "UpdateWorkingDaysJob"
    schedule: "30 1 * * *"
