trim_sessions_job:
  cron: "0 2 * * *"
  class: TrimSessionsJob

update_working_days_since_submission:
  cron: "0 3 * * *"
  class: UpdateWorkingDaysJob

expire_further_information_requests:
  cron: "0 2 * * *"
  class: ExpireFurtherInformationRequestsJob
