trim_sessions_job:
  cron: "0 1 * * *"
  class: TrimSessionsJob

destroy_application_forms:
  cron: "15 1 * * *"
  class: DestroyApplicationFormsJobs

update_working_days_since_submission:
  cron: "30 1 * * *"
  class: UpdateWorkingDaysJob

expire_further_information_requests:
  cron: "0 2 * * *"
  class: ExpireRequestablesJob
  args: ["FurtherInformationRequest"]

expire_professional_standing_requests:
  cron: "10 2 * * *"
  class: ExpireRequestablesJob
  args: ["ProfessionalStandingRequest"]

expire_reference_requests:
  cron: "20 2 * * *"
  class: ExpireRequestablesJob
  args: ["ReferenceRequest"]

send_further_information_request_reminders:
  cron: "0 3 * * *"
  class: SendFurtherInformationRequestRemindersJob
