trim_sessions_job:
  cron: "0 1 * * *"
  class: TrimSessionsJob
expire_further_information_requests:
  cron: "0 2 * * *"
  class: ExpireFurtherInformationRequestsJob
update_working_days_since_submission:
  cron: "0 3 * * *"
  class: UpdateWorkingDaysJob
send_further_information_request_reminders:
  cron: "0 4 * * *"
  class: SendFurtherInformationRequestRemindersJob
