name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy environment ( dev or test or preprod or production )"
        required: true
        default: dev
        type: environment
        options:
          - dev
          - test
          - preprod
          - production
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - labeled
      - synchronize
      - reopened
      - opened
env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  docker:
    if: contains(github.event.pull_request.labels.*.name, 'deploy') || github.event_name != 'pull_request'
    name: Docker build and push
    runs-on: ubuntu-latest
    outputs:
      docker_image: ${{ steps.image.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker image tag
        id: image
        run: |
          echo ::set-output name=tag::$CONTAINER_REGISTRY/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):$GITHUB_SHA

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build & push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.image.outputs.tag }}

  deploy_dev:
    name: Deploy to dev environment
    needs: [docker]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: dev
      url: ${{ steps.deploy.outputs.environment_url }}
    concurrency: deploy_dev

    outputs:
      environment_url: ${{ steps.deploy.outputs.environment_url }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/deploy-environment
        id: deploy
        with:
          environment_name: dev
          docker_image: ${{ needs.docker.outputs.docker_image }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          terraform_vars: workspace_variables/dev.tfvars.json

  deploy_review:
    name: Deploy to review environment
    concurrency: deploy_review_${{ github.event.pull_request.number }}
    needs: [docker]
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'deploy') || github.event_name != 'pull_request'
    environment:
      name: review

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/deploy-environment
        id: deploy
        with:
          environment_name: review
          docker_image: ${{ needs.docker.outputs.docker_image }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          pr_id: ${{ github.event.pull_request.number }}

      - name: Post sticky pull request comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Review app deployed to ${{ steps.deploy.outputs.environment_url }}

  deploy_environment:
    name: Deploy to ${{ github.event.inputs.environment }} environment
    runs-on: ubuntu-latest
    needs: [docker]
    if: github.event_name == 'workflow_dispatch'
    environment:
      name: ${{ github.event.inputs.environment }}
      url: ${{ steps.deploy.outputs.environment_url }}
    concurrency: deploy_${{ github.event.inputs.environment }}

    outputs:
      environment_url: ${{ steps.deploy.outputs.environment_url }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/deploy-environment
        id: deploy
        with:
          environment_name: ${{ github.event.inputs.environment }}
          docker_image: ${{ needs.docker.outputs.docker_image }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
