name: Fake data

on:
  workflow_dispatch:
    inputs:
      environment:
        description: GitHub environment to regenerate example data
        type: choice
        default: test
        options:
          - development
          - test

jobs:
  regenerate:
    name: Regenerate
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: ./.github/actions/set-kubernetes-credentials
        with:
          environment: ${{ github.event.inputs.environment }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Seed database and regenerate example data
        run: |
          kubectl exec \
            -n tra-${{ github.event.inputs.environment }} \
            deployment/apply-for-qts-${{ github.event.inputs.environment }}-web \
            -- sh -c "cd /app && /usr/local/bin/bundle exec rails fake_data:regenerate"
