name: Lint

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare application environment
        uses: ./.github/actions/prepare-app-env

      - name: Run Prettier
        run: yarn prettier --check --ignore-unknown '**/*'

  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare application environment
        uses: ./.github/actions/prepare-app-env

      - name: Run Rubocop
        run: bin/bundle exec rubocop

  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.10

      - name: Check formatting
        run: terraform fmt -check
        working-directory: terraform

      - name: Validate
        run: |
          terraform init -backend=false
          terraform validate -no-color
        working-directory: terraform
